# -*- coding: utf-8 -*-
"""NovelAILeaks API Backend (4chan Ver.)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Ma71L6uGbtt6UQyA3FjqW2lcZ5Bjck-

基于 4chan 魔改版 NovelAILeaks (naifu) 制作。[来源](https://boards.4channel.org/g/thread/89095460#p89097704)

使用官方前端 + 优化版后端，可突破75限制，支持所有模型。

Credit: https://t.me/StableDiffusion_CN https://t.me/exlolicon

Thanks: Anonymous, 炼铜术士, 神楽坂早苗️, Jonathan, 咕 咕, 猫又逆变器, Gaein nidb
"""

#@title ### 0. 检查 GPU 工作状态

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
#@title ### 1. 下载 Novel AI API 后端、模型 
#@markdown 如果下载速度太慢可尝试 restart

# %cd /content/
!apt install -y -qq aria2
!aria2c --summary-interval=5 -x 3 --allow-overwrite=true -Z \
  https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/naifu.tar \
  https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animefull-latest.tar 
  
!echo "Decompressing..."
!tar xf naifu.tar && rm naifu.tar
!echo "Done."

# Commented out IPython magic to ensure Python compatibility.
#@title ### 2. 安装依赖
#@markdown 耐心等待安装完成

# %cd /content/naifu
!pip install virtualenv && bash ./setup.sh
!curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.0/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz | tar zx -C /usr/bin
!curl -Lo /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x /usr/bin/cloudflared
!/content/naifu/venv/bin/python -m pip install -qq pytorch_lightning==1.7.7

# Commented out IPython magic to ensure Python compatibility.
#@title ### 3. 启动模型
#@markdown 访问输出的映射地址（以 `trycloudflare.com` / `bore.pub` 结尾）即可。
#@markdown - 请等待模型加载完成（出现`Application startup complete`字样）再访问
#@markdown - cloudflare 提供的服务偶尔会出现请求超时，可换用 bore 隧道

# %cd /content/naifu
!sed -i 's/# export SAVE_FILES="1"/export SAVE_FILES="1"/g' run.sh
!bash run.sh & cloudflared tunnel --url localhost:6969

# Commented out IPython magic to ensure Python compatibility.
#@title ### 4. （可选）使用 7G 的 `animefull-latest` 模型运行
#@markdown 默认使用的是 4G 大小的 animefull-final-pruned 模型。如果想使用 7G 的 animefull-latest 模型，运行这个

# %cd /content/
!mkdir /content/naifu/models/animefull-latest
!tar xf animefull-latest.tar -C /content/naifu/models/animefull-latest && rm animefull-latest.tar
!sed -i 's/map_location="cpu"/map_location="cuda"/g' /content/naifu/hydra_node/models.py

# %cd /content/naifu
# %env DTYPE=float16
# %env CLIP_CONTEXTS=3
# %env AMP=1
# %env MODEL=stable-diffusion
# %env DEV=True
# %env MODEL_PATH=models/animefull-latest
# %env ENABLE_EMA=1
# %env VAE_PATH=models/animevae.pt
# %env PENULTIMATE=1
# %env PYTHONDONTWRITEBYTECODE=1
# %env SAVE_FILES=1

!./venv/bin/python -m uvicorn --host 0.0.0.0 --port=6969 main:app & bore local 6969 --to bore.pub & cloudflared tunnel --url localhost:6969